services:
  db:
    image: postgres:16-alpine
    container_name: db
    env_file: .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - ./static/media:/app/media

  frontend:
    build: ./frontend
    container_name: frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ./static:/static/

  gateway:
    build: ./nginx
    container_name: gateway
    env_file: .env
    ports:
      - "9900:80"
    volumes:
      - ./static:/staticfiles
